objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_On_Market__c</fullName>
        <formula>TODAY() - Date_Listed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days On Market</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PropertyUtility.cls
public class PropertyUtility {
    public static void  newListedProperties(){
        string propEmail;
        list<Property__c> newPropList = [select name,
                                     Broker__r.Email__c,
                                     Days_On_Market__c from 
                                     Property__c
                                     where Days_On_Market__c <= 30];
        for (Property__c ListofProp : newPropList){
            propEmail = ListofProp.Name + ':' + ListOfProp.Broker__r.Email__c;
        }
        system.debug('Property Email'+propEmail);
    }
}